sudo: true
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
# services: mongodb
script: sbt ";project respite-core; clean; coverage; test"
after_success: sbt "project respite-core" coveralls
env:
  global:
  - MONGO_PORT=27017
  - secure: d+Jo3HwjYCnpHLWFr0bsauv0/5OhKl0iSFlGlRo0Ybnv6ii9jo5qYUSV9gVXRFlypOfEmu3gCNzv6GxTLZsTivV38qpVJypDV0N1cGUl7nRmTanU0Ba9LjtusD6dCRqbfOhggdk4mNf7KFNJ6DA1NQHCRuwmOBCLtebu6WaMC5Y=
  - secure: LumeI7Zr5Cpotm9pLv3F8116Vt5FwhITfnnqhTCA7iXcHVHVuUz+8mVk3PHuL45Nmbcpivc6B80DhFC5JqeXU3CCrftEETmH29A1uJlS6qkpfj6HjeN1yPVG4qCRWUM0Y/GlDkxH+DlTt5UCTPmRmR5OduLoZYT8iFnrE/74gfA=
  - secure: IcZGkHw+qgLT/fHvw7Ifae7SRFybRFLXmA5zsaXBhKTSVTLTd7aTHrEau0+bkEBzk1Nu7SZKZMthV0JDJ+wwPCky5F7KLVX/Tqo9zJK/IJRqVKNtIRLUqb/9HlWyl11AgyZhE+6RcOATaEfDk1ncqye2ZkoKDlhOnTNZSqxCYBc=
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - mongod --version