# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Respite
tagline:          'A reactive and modular micro-framework for REST apps in Scala'
description:      'A reactive and modular micro-framework for REST apps written in Scala. Made with &hearts; by <a href="https://twitter.com/matthewfellows" target="_blank">@matthewfellows</a>.'
url:              https://github.com/mefellows/respite
baseurl:          /respite

author:
  name:           'Matt Fellows'
  url:            https://twitter.com/matthewfellows

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/mefellows/respite
